import { Application } from '../declarations';
import users from './users/users.service';
import cartorios from './cartorios/cartorios.service';
import ac from './ac/ac.service';
import al from './al/al.service';
import ap from './ap/ap.service';
import am from './am/am.service';
import ba from './ba/ba.service';
import ce from './ce/ce.service';
import df from './df/df.service';
import es from './es/es.service';
import go from './go/go.service';
import ma from './ma/ma.service';
import mt from './mt/mt.service';
import ms from './ms/ms.service';
import mg from './mg/mg.service';
import pa from './pa/pa.service';
import pb from './pb/pb.service';
import pr from './pr/pr.service';
import pe from './pe/pe.service';
import pi from './pi/pi.service';
import rj from './rj/rj.service';
import rn from './rn/rn.service';
import rs from './rs/rs.service';
import ro from './ro/ro.service';
import rr from './rr/rr.service';
import sc from './sc/sc.service';
import sp from './sp/sp.service';
import se from './se/se.service';
import to from './to/to.service';
// Don't remove this comment. It's needed to format import lines nicely.

export default function (app: Application) {
  app.configure(users);
  app.configure(cartorios);
  app.configure(ac);
  app.configure(al);
  app.configure(ap);
  app.configure(am);
  app.configure(ba);
  app.configure(ce);
  app.configure(df);
  app.configure(es);
  app.configure(go);
  app.configure(ma);
  app.configure(mt);
  app.configure(ms);
  app.configure(mg);
  app.configure(pa);
  app.configure(pb);
  app.configure(pr);
  app.configure(pe);
  app.configure(pi);
  app.configure(rj);
  app.configure(rn);
  app.configure(rs);
  app.configure(ro);
  app.configure(rr);
  app.configure(sc);
  app.configure(sp);
  app.configure(se);
  app.configure(to);
}
